import streamlit as st
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from gemini_agent import GeminiAgent

# ---------------------------------------------------------
# PAGE CONFIG
# ---------------------------------------------------------
st.set_page_config(page_title="Student Performance AI Agent", layout="wide")
st.title("🎓 Student Performance Prediction + AI Summary")


# ---------------------------------------------------------
# LOAD DATA
# ---------------------------------------------------------
@st.cache_data
def load_data():
    df = pd.read_csv("masked_data.csv")

    # detect categorical columns
    cat_cols = df.select_dtypes(include="object").columns.tolist()

    # create encoders
    encoders = {}
    for col in cat_cols:
        enc = LabelEncoder()
        df[col] = enc.fit_transform(df[col].astype(str))
        encoders[col] = enc

    return df, encoders, cat_cols


df, encoders, cat_cols = load_data()

st.success("✔ Dataset loaded & encoded successfully")


# ---------------------------------------------------------
# TRAIN MODEL
# ---------------------------------------------------------
@st.cache_resource
def train_model(df):
    X = df.drop("Grade", axis=1)
    y = df["Grade"]

    model = RandomForestClassifier(n_estimators=300, random_state=42)
    model.fit(X, y)

    return model, X.columns


model, feature_cols = train_model(df)
st.success("✔ Model trained successfully")


# ---------------------------------------------------------
# UI INPUT — AUTOGENERATED FROM DATASET VALUES
# ---------------------------------------------------------
st.header("📥 Enter Student Details")

user_inputs = {}

for col in feature_cols:
    # skip target
    if col == "Grade":
        continue

    if col in cat_cols:
        # get original category names
        original_values = encoders[col].classes_.tolist()
        val = st.selectbox(col, original_values)
        # encode to numeric
        encoded_val = encoders[col].transform([val])[0]
        user_inputs[col] = encoded_val
    else:
        # numeric feature
        min_v = float(df[col].min())
        max_v = float(df[col].max())
        default_v = float(df[col].mean())

        val = st.number_input(col, min_value=min_v, max_value=max_v, value=default_v)
        user_inputs[col] = val

# convert into DF
input_df = pd.DataFrame([user_inputs])


# ---------------------------------------------------------
# PREDICT
# ---------------------------------------------------------
if st.button("Predict Grade"):
    pred_encoded = model.predict(input_df)[0]

    # Decode grade using the encoder
    grade_label = encoders["Grade"].inverse_transform([pred_encoded])[0]

    st.subheader("🎯 Predicted Grade")
    st.metric("Grade", grade_label)

    # -----------------------------------------------------
    # GEMINI SUMMARY
    # -----------------------------------------------------
    st.divider()
    with st.expander("✨ AI Agent Summary (Gemini)"):
        api_key = st.text_input("Enter Gemini API Key", type="password")

        if api_key:
            agent = GeminiAgent(api_key)

            readable_inputs = {
                col: encoders[col].inverse_transform([int(val)])[0]
                if col in cat_cols else val
                for col, val in user_inputs.items()
            }

            summary = agent.summarize_prediction(readable_inputs, grade_label)
            st.write(summary)

        else:
            st.info("Enter Gemini API key to generate AI summary.")

st.caption("Built with ❤️ using Streamlit + RandomForest + Gemini AI")
